-- Russian names for free-exercise-db imports (873 rows).
-- Auto-translated (Google). Updates only fedb-* rows; curated ex-NNN
-- rows are untouched. Idempotent — safe to re-run.
-- Run in Supabase SQL Editor on BOTH staging and production.

UPDATE exercises_library AS e
SET name_ru = v.ru
FROM (VALUES
('fedb-3_4_Sit-Up', '3/4 приседания'),
('fedb-90_90_Hamstring', '90/90 Подколенное сухожилие'),
('fedb-Ab_Crunch_Machine', 'Машина для пресса'),
('fedb-Ab_Roller', 'Аб Роллер'),
('fedb-Adductor', 'Аддуктор'),
('fedb-Adductor_Groin', 'Аддуктор/Пах'),
('fedb-Advanced_Kettlebell_Windmill', 'Усовершенствованная ветряная мельница с гирями'),
('fedb-Air_Bike', 'Воздушный велосипед'),
('fedb-All_Fours_Quad_Stretch', 'Растяжка на четвереньках'),
('fedb-Alternate_Hammer_Curl', 'Альтернативное сгибание молотка'),
('fedb-Alternate_Heel_Touchers', 'Альтернативные касания пятки'),
('fedb-Alternate_Incline_Dumbbell_Curl', 'Поочередное сгибание рук с гантелями на наклонной скамье'),
('fedb-Alternate_Leg_Diagonal_Bound', 'Альтернативная нога по диагонали'),
('fedb-Alternating_Cable_Shoulder_Press', 'Попеременный жим от плеч на тросе'),
('fedb-Alternating_Deltoid_Raise', 'Попеременный подъем дельтовидных мышц'),
('fedb-Alternating_Floor_Press', 'Попеременный жим с пола'),
('fedb-Alternating_Hang_Clean', 'Поочередное подвешивание на чистку'),
('fedb-Alternating_Kettlebell_Press', 'Попеременный жим гири'),
('fedb-Alternating_Kettlebell_Row', 'Поочередная тяга гири'),
('fedb-Alternating_Renegade_Row', 'Альтернативный ряд отступников'),
('fedb-Ankle_Circles', 'Круги на лодыжке'),
('fedb-Ankle_On_The_Knee', 'Лодыжка на колене'),
('fedb-Anterior_Tibialis-SMR', 'Передняя большеберцовая мышца-SMR'),
('fedb-Anti-Gravity_Press', 'Антигравитационный пресс'),
('fedb-Arm_Circles', 'Круги руками'),
('fedb-Arnold_Dumbbell_Press', 'Жим гантелей Арнольда'),
('fedb-Around_The_Worlds', 'Вокруг света'),
('fedb-Atlas_Stone_Trainer', 'Тренер по камню Атласа'),
('fedb-Atlas_Stones', 'Камни Атласа'),
('fedb-Axle_Deadlift', 'Становая тяга на оси'),
('fedb-Back_Flyes_-_With_Bands', 'Обратные мухи - с лентами'),
('fedb-Backward_Drag', 'Перетаскивание назад'),
('fedb-Backward_Medicine_Ball_Throw', 'Бросок медицинского мяча назад'),
('fedb-Balance_Board', 'Балансовая доска'),
('fedb-Ball_Leg_Curl', 'Сгибание ног с мячом'),
('fedb-Band_Assisted_Pull-Up', 'Подтягивания с резинкой'),
('fedb-Band_Good_Morning', 'Группа «Доброе утро»'),
('fedb-Band_Good_Morning_Pull_Through', 'Группа «Доброе утро» (Пройти)'),
('fedb-Band_Hip_Adductions', 'Приведение бандажа в бедро'),
('fedb-Band_Pull_Apart', 'Группа растягивается'),
('fedb-Band_Skull_Crusher', 'Ленточная дробилка черепов'),
('fedb-Barbell_Ab_Rollout', 'Разворот пресса со штангой'),
('fedb-Barbell_Ab_Rollout_-_On_Knees', 'Выкатывание пресса со штангой – на коленях'),
('fedb-Barbell_Bench_Press_-_Medium_Grip', 'Жим штанги лежа — средний хват'),
('fedb-Barbell_Curl', 'Сгибание рук со штангой'),
('fedb-Barbell_Curls_Lying_Against_An_Incline', 'Сгибания рук со штангой лежа на наклонной поверхности'),
('fedb-Barbell_Deadlift', 'Становая тяга со штангой'),
('fedb-Barbell_Full_Squat', 'Полный присед со штангой'),
('fedb-Barbell_Glute_Bridge', 'Ягодичный мостик со штангой'),
('fedb-Barbell_Guillotine_Bench_Press', 'Гильотинный жим штанги лежа'),
('fedb-Barbell_Hack_Squat', 'Гакк-приседания со штангой'),
('fedb-Barbell_Hip_Thrust', 'Тяга бедра со штангой'),
('fedb-Barbell_Incline_Bench_Press_-_Medium_Grip', 'Жим штанги на наклонной скамье — средний хват'),
('fedb-Barbell_Incline_Shoulder_Raise', 'Подъем плеч со штангой на наклоне'),
('fedb-Barbell_Lunge', 'Выпады со штангой'),
('fedb-Barbell_Rear_Delt_Row', 'Тяга задних дельт со штангой'),
('fedb-Barbell_Rollout_from_Bench', 'Выкат штанги из лежа'),
('fedb-Barbell_Seated_Calf_Raise', 'Подъем на носки со штангой сидя'),
('fedb-Barbell_Shoulder_Press', 'Жим штанги от плеч'),
('fedb-Barbell_Shrug', 'Шраги со штангой'),
('fedb-Barbell_Shrug_Behind_The_Back', 'Шраги со штангой за спиной'),
('fedb-Barbell_Side_Bend', 'Боковой наклон штанги'),
('fedb-Barbell_Side_Split_Squat', 'Приседания со штангой на боку'),
('fedb-Barbell_Squat', 'Приседания со штангой'),
('fedb-Barbell_Squat_To_A_Bench', 'Приседания со штангой на скамье'),
('fedb-Barbell_Step_Ups', 'Подъемы со штангой'),
('fedb-Barbell_Walking_Lunge', 'Ходьба со штангой, выпады'),
('fedb-Battling_Ropes', 'Боевые веревки'),
('fedb-Bear_Crawl_Sled_Drags', 'Сани для ползания медведя'),
('fedb-Behind_Head_Chest_Stretch', 'Растяжка груди за головой'),
('fedb-Bench_Dips', 'Отжимания на скамейке'),
('fedb-Bench_Jump', 'Прыжок на скамейке'),
('fedb-Bench_Press_-_Powerlifting', 'Жим лежа — пауэрлифтинг'),
('fedb-Bench_Press_-_With_Bands', 'Жим лежа – с лентами'),
('fedb-Bench_Press_with_Chains', 'Жим лежа с цепями'),
('fedb-Bench_Sprint', 'Спринт на скамье'),
('fedb-Bent-Arm_Barbell_Pullover', 'Пуловер со штангой на согнутых руках'),
('fedb-Bent-Arm_Dumbbell_Pullover', 'Пуловер с гантелями на согнутых руках'),
('fedb-Bent-Knee_Hip_Raise', 'Подъем бедра с согнутым коленом'),
('fedb-Bent_Over_Barbell_Row', 'Тяга штанги в наклоне'),
('fedb-Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench', 'Подъем задних дельт с гантелью в наклоне, голова на скамье'),
('fedb-Bent_Over_Low-Pulley_Side_Lateral', 'Наклон в сторону с низким шкивом, боковая сторона'),
('fedb-Bent_Over_One-Arm_Long_Bar_Row', 'Тяга штанги на одной руке в наклоне'),
('fedb-Bent_Over_Two-Arm_Long_Bar_Row', 'Тяга штанги двумя руками в наклоне'),
('fedb-Bent_Over_Two-Dumbbell_Row', 'Тяга двух гантелей в наклоне'),
('fedb-Bent_Over_Two-Dumbbell_Row_With_Palms_In', 'Тяга двух гантелей в наклоне ладонями внутрь'),
('fedb-Bent_Press', 'Бент Пресс'),
('fedb-Bicycling', 'Езда на велосипеде'),
('fedb-Bicycling_Stationary', 'Велосипед, Стационарный'),
('fedb-Board_Press', 'Совет Пресс'),
('fedb-Body-Up', 'Боди-ап'),
('fedb-Body_Tricep_Press', 'Жим на трицепс для тела'),
('fedb-Bodyweight_Flyes', 'Полеты с собственным весом'),
('fedb-Bodyweight_Mid_Row', 'Средний ряд с собственным весом'),
('fedb-Bodyweight_Squat', 'Приседания с собственным весом'),
('fedb-Bodyweight_Walking_Lunge', 'Ходьба с выпадами с собственным весом'),
('fedb-Bosu_Ball_Cable_Crunch_With_Side_Bends', 'Bosu Ball Crunch с боковыми изгибами'),
('fedb-Bottoms-Up_Clean_From_The_Hang_Position', 'Подъём снизу вверх из виса'),
('fedb-Bottoms_Up', 'снизу вверх'),
('fedb-Box_Jump_Multiple_Response', 'Прыжок в коробку (множественный ответ)'),
('fedb-Box_Skip', 'Пропустить коробку'),
('fedb-Box_Squat', 'Приседания на ящик'),
('fedb-Box_Squat_with_Bands', 'Приседания на ящик с лентами'),
('fedb-Box_Squat_with_Chains', 'Приседания на ящик с цепями'),
('fedb-Brachialis-SMR', 'Брахиалис-СМР'),
('fedb-Bradford_Rocky_Presses', 'Брэдфорд / Рокки Прессс'),
('fedb-Butt-Ups', 'Попки'),
('fedb-Butt_Lift_Bridge', 'Подтяжка ягодиц (Мост)'),
('fedb-Butterfly', 'Бабочка'),
('fedb-Cable_Chest_Press', 'Кабельный жим от груди'),
('fedb-Cable_Crossover', 'Кабельный кроссовер'),
('fedb-Cable_Crunch', 'Кабельный хруст'),
('fedb-Cable_Deadlifts', 'Кабельная становая тяга'),
('fedb-Cable_Hammer_Curls_-_Rope_Attachment', 'Сгибания троса с молотком – крепление веревки'),
('fedb-Cable_Hip_Adduction', 'Кабельное приведение бедра'),
('fedb-Cable_Incline_Pushdown', 'Наклон троса при опускании'),
('fedb-Cable_Incline_Triceps_Extension', 'Разгибание трицепса на тросе на наклонной скамье'),
('fedb-Cable_Internal_Rotation', 'Внутреннее вращение кабеля'),
('fedb-Cable_Iron_Cross', 'Кабель Железный Крест'),
('fedb-Cable_Judo_Flip', 'Кабельное дзюдо-флип'),
('fedb-Cable_Lying_Triceps_Extension', 'Разгибание трицепса лежа на кабеле'),
('fedb-Cable_One_Arm_Tricep_Extension', 'Разгибание трицепса одной руки на тросе'),
('fedb-Cable_Preacher_Curl', 'Кабельный проповедник Керл'),
('fedb-Cable_Rear_Delt_Fly', 'Разведение задних дельт на тросе'),
('fedb-Cable_Reverse_Crunch', 'Кабельный обратный кранч'),
('fedb-Cable_Rope_Overhead_Triceps_Extension', 'Разгибание трицепса над головой на тросе'),
('fedb-Cable_Rope_Rear-Delt_Rows', 'Тяга задних дельт со скакалкой'),
('fedb-Cable_Russian_Twists', 'Кабельные русские витки'),
('fedb-Cable_Seated_Crunch', 'Кранч сидя на тросе'),
('fedb-Cable_Seated_Lateral_Raise', 'Боковой подъем сидя на тросе'),
('fedb-Cable_Shoulder_Press', 'Кабельный жим от плеч'),
('fedb-Cable_Shrugs', 'Кабельные шраги'),
('fedb-Cable_Wrist_Curl', 'Сгибание запястий на тросе'),
('fedb-Calf-Machine_Shoulder_Shrug', 'Пожимание плечами для икроножных мышц'),
('fedb-Calf_Press', 'Пресс для телят'),
('fedb-Calf_Press_On_The_Leg_Press_Machine', 'Жим икр на тренажере для жима ногами'),
('fedb-Calf_Raise_On_A_Dumbbell', 'Подъем на носки с гантелью'),
('fedb-Calf_Raises_-_With_Bands', 'Подъемы на носки – с лентами'),
('fedb-Calf_Stretch_Elbows_Against_Wall', 'Растягивание икроножных локтей у стены'),
('fedb-Calf_Stretch_Hands_Against_Wall', 'Теленок тянется руками к стене'),
('fedb-Calves-SMR', 'Телята-SMR'),
('fedb-Car_Deadlift', 'Становая тяга на автомобиле'),
('fedb-Car_Drivers', 'Водители автомобилей'),
('fedb-Carioca_Quick_Step', 'Кариока Квик Степ'),
('fedb-Cat_Stretch', 'Кошачья растяжка'),
('fedb-Catch_and_Overhead_Throw', 'Ловля и бросок через голову'),
('fedb-Chain_Handle_Extension', 'Удлинитель цепной ручки'),
('fedb-Chain_Press', 'Цепной пресс'),
('fedb-Chair_Leg_Extended_Stretch', 'Вытянутая ножка стула'),
('fedb-Chair_Lower_Back_Stretch', 'Растяжка нижней части спины на стуле'),
('fedb-Chair_Squat', 'Приседания на стуле'),
('fedb-Chair_Upper_Body_Stretch', 'Растяжка верхней части тела стула'),
('fedb-Chest_And_Front_Of_Shoulder_Stretch', 'Растяжка груди и передней части плеч'),
('fedb-Chest_Push_from_3_point_stance', 'Толчок грудью из трехточечной позиции'),
('fedb-Chest_Push_multiple_response', 'Толчок от груди (множественный ответ)'),
('fedb-Chest_Push_single_response', 'Толчок от груди (один ответ)'),
('fedb-Chest_Push_with_Run_Release', 'Толчок от груди с разбегом'),
('fedb-Chest_Stretch_on_Stability_Ball', 'Растяжка груди на мяче для стабилизации'),
('fedb-Childs_Pose', 'Детская поза'),
('fedb-Chin-Up', 'Подтягивания'),
('fedb-Chin_To_Chest_Stretch', 'Растяжка подбородка к груди'),
('fedb-Circus_Bell', 'Цирковой колокол'),
('fedb-Clean', 'Чистый'),
('fedb-Clean_Deadlift', 'Чистая становая тяга'),
('fedb-Clean_Pull', 'Чистая тяга'),
('fedb-Clean_Shrug', 'Чистое пожатие плечами'),
('fedb-Clean_and_Jerk', 'Чистота и рывок'),
('fedb-Clean_and_Press', 'Очистите и нажмите'),
('fedb-Clean_from_Blocks', 'Очистить от блоков'),
('fedb-Clock_Push-Up', 'Отжимания на часах'),
('fedb-Close-Grip_Barbell_Bench_Press', 'Жим штанги узким хватом'),
('fedb-Close-Grip_Dumbbell_Press', 'Жим гантелей узким хватом'),
('fedb-Close-Grip_EZ-Bar_Curl_with_Band', 'Сгибания рук на EZ-грифе с лентой узким хватом'),
('fedb-Close-Grip_EZ-Bar_Press', 'Жим EZ-штанги узким хватом'),
('fedb-Close-Grip_EZ_Bar_Curl', 'Сгибание рук на грифе EZ узким хватом'),
('fedb-Close-Grip_Front_Lat_Pulldown', 'Тяга широчайших передних мышц узким хватом'),
('fedb-Close-Grip_Push-Up_off_of_a_Dumbbell', 'Отжимания узким хватом от гантели'),
('fedb-Close-Grip_Standing_Barbell_Curl', 'Сгибание штанги узким хватом стоя'),
('fedb-Cocoons', 'Коконы'),
('fedb-Conans_Wheel', 'Колесо Конана'),
('fedb-Concentration_Curls', 'Концентрированные кудри'),
('fedb-Cross-Body_Crunch', 'Скручивание через плечо'),
('fedb-Cross_Body_Hammer_Curl', 'Сгибание молотка через плечо'),
('fedb-Cross_Over_-_With_Bands', 'Кроссовер – с лентами'),
('fedb-Crossover_Reverse_Lunge', 'Кроссовер Обратный выпад'),
('fedb-Crucifix', 'Распятие'),
('fedb-Crunch_-_Hands_Overhead', 'Кранч – руки над головой'),
('fedb-Crunch_-_Legs_On_Exercise_Ball', 'Кранч – ноги на мяче для упражнений'),
('fedb-Crunches', 'Скручивания'),
('fedb-Cuban_Press', 'Кубинская пресса'),
('fedb-Dancers_Stretch', 'Растяжка танцора'),
('fedb-Dead_Bug', 'Мертвая ошибка'),
('fedb-Deadlift_with_Bands', 'Становая тяга с лентами'),
('fedb-Deadlift_with_Chains', 'Становая тяга с цепями'),
('fedb-Decline_Barbell_Bench_Press', 'Жим штанги лежа'),
('fedb-Decline_Close-Grip_Bench_To_Skull_Crusher', 'Отклонить жим узким хватом на Skull Crusher'),
('fedb-Decline_Crunch', 'Снижение кранча'),
('fedb-Decline_Dumbbell_Bench_Press', 'Жим гантелей на наклонной скамье'),
('fedb-Decline_Dumbbell_Flyes', 'Разведение гантелей на наклоне'),
('fedb-Decline_Dumbbell_Triceps_Extension', 'Разгибание трицепса с гантелью на наклоне'),
('fedb-Decline_EZ_Bar_Triceps_Extension', 'Разгибание трицепса на наклонной штанге EZ'),
('fedb-Decline_Oblique_Crunch', 'Косое скручивание на наклоне'),
('fedb-Decline_Push-Up', 'Отказ от отжиманий'),
('fedb-Decline_Reverse_Crunch', 'Снижение обратного кранча'),
('fedb-Decline_Smith_Press', 'Отказ Смит Пресс'),
('fedb-Deficit_Deadlift', 'Дефицит становой тяги'),
('fedb-Depth_Jump_Leap', 'Прыжок в глубину'),
('fedb-Dip_Machine', 'Машина для погружения'),
('fedb-Dips_-_Chest_Version', 'Отжимания - версия для груди'),
('fedb-Dips_-_Triceps_Version', 'Отжимания - версия для трицепса'),
('fedb-Donkey_Calf_Raises', 'Подъемы на носки осла'),
('fedb-Double_Kettlebell_Alternating_Hang_Clean', 'Двойная гиря, попеременный вис на чистоте'),
('fedb-Double_Kettlebell_Jerk', 'Двойной толчок гири'),
('fedb-Double_Kettlebell_Push_Press', 'Жим двойной гири'),
('fedb-Double_Kettlebell_Snatch', 'Рывок двойной гири'),
('fedb-Double_Kettlebell_Windmill', 'Ветряная мельница с двойной гирей'),
('fedb-Double_Leg_Butt_Kick', 'Двойной удар ногой в задницу'),
('fedb-Downward_Facing_Balance', 'Баланс лицом вниз'),
('fedb-Drag_Curl', 'Перетащите завиток'),
('fedb-Drop_Push', 'падение толчок'),
('fedb-Dumbbell_Alternate_Bicep_Curl', 'Поочередное сгибание рук на бицепс с гантелью'),
('fedb-Dumbbell_Bench_Press', 'Жим гантелей лежа'),
('fedb-Dumbbell_Bench_Press_with_Neutral_Grip', 'Жим гантелей лежа нейтральным хватом'),
('fedb-Dumbbell_Bicep_Curl', 'Сгибание рук с гантелью на бицепс'),
('fedb-Dumbbell_Clean', 'Гантели чистые'),
('fedb-Dumbbell_Floor_Press', 'Жим гантелей с пола'),
('fedb-Dumbbell_Flyes', 'Разведение гантелей'),
('fedb-Dumbbell_Incline_Row', 'Тяга гантелей на наклонной скамье'),
('fedb-Dumbbell_Incline_Shoulder_Raise', 'Подъем плеч с гантелями на наклоне'),
('fedb-Dumbbell_Lunges', 'Выпады с гантелями'),
('fedb-Dumbbell_Lying_One-Arm_Rear_Lateral_Raise', 'Подъем гантели лежа на одной руке сзади в стороны'),
('fedb-Dumbbell_Lying_Pronation', 'Пронация с гантелью лёжа'),
('fedb-Dumbbell_Lying_Rear_Lateral_Raise', 'Подъем гантели лежа сзади в стороны'),
('fedb-Dumbbell_Lying_Supination', 'Супинация с гантелью лёжа'),
('fedb-Dumbbell_One-Arm_Shoulder_Press', 'Жим гантели одной рукой от плеч'),
('fedb-Dumbbell_One-Arm_Triceps_Extension', 'Разгибание трицепса одной рукой с гантелью'),
('fedb-Dumbbell_One-Arm_Upright_Row', 'Тяга гантели на одной руке вертикально'),
('fedb-Dumbbell_Prone_Incline_Curl', 'Сгибание рук с гантелями на наклоне лежа'),
('fedb-Dumbbell_Raise', 'Подъем гантели'),
('fedb-Dumbbell_Rear_Lunge', 'Выпады сзади с гантелями'),
('fedb-Dumbbell_Scaption', 'Скапшн с гантелями'),
('fedb-Dumbbell_Seated_Box_Jump', 'Прыжок на коробку с гантелями сидя'),
('fedb-Dumbbell_Seated_One-Leg_Calf_Raise', 'Подъем гантели на одной ноге сидя'),
('fedb-Dumbbell_Shoulder_Press', 'Жим гантелей от плеч'),
('fedb-Dumbbell_Shrug', 'Шраги с гантелями'),
('fedb-Dumbbell_Side_Bend', 'Наклон гантели в сторону'),
('fedb-Dumbbell_Squat', 'Приседания с гантелями'),
('fedb-Dumbbell_Squat_To_A_Bench', 'Приседания с гантелями на скамье'),
('fedb-Dumbbell_Step_Ups', 'Подъёмы с гантелями'),
('fedb-Dumbbell_Tricep_Extension_-Pronated_Grip', 'Разгибание трицепса с гантелью — хват с пронацией'),
('fedb-Dynamic_Back_Stretch', 'Динамическая растяжка спины'),
('fedb-Dynamic_Chest_Stretch', 'Динамическая растяжка груди'),
('fedb-EZ-Bar_Curl', 'Сгибание рук на грифе EZ'),
('fedb-EZ-Bar_Skullcrusher', 'EZ-Bar Skullcrusher'),
('fedb-Elbow_Circles', 'Круги локтями'),
('fedb-Elbow_to_Knee', 'От локтя до колена'),
('fedb-Elbows_Back', 'Локти назад'),
('fedb-Elevated_Back_Lunge', 'Приподнятый выпад назад'),
('fedb-Elevated_Cable_Rows', 'Надземные кабельные ряды'),
('fedb-Elliptical_Trainer', 'Эллиптический тренажер'),
('fedb-Exercise_Ball_Crunch', 'Упражнение «Скручивание мяча»'),
('fedb-Exercise_Ball_Pull-In', 'Упражнение «Подтягивание мяча»'),
('fedb-Extended_Range_One-Arm_Kettlebell_Floor_Press', 'Жим гири с пола расширенной амплитуды одной рукой'),
('fedb-External_Rotation', 'Внешнее вращение'),
('fedb-External_Rotation_with_Band', 'Внешнее вращение с лентой'),
('fedb-External_Rotation_with_Cable', 'Внешнее вращение с помощью троса'),
('fedb-Face_Pull', 'Подтягивание лица'),
('fedb-Farmers_Walk', 'Фермерская прогулка'),
('fedb-Fast_Skipping', 'Быстрый пропуск'),
('fedb-Finger_Curls', 'Сгибания пальцев'),
('fedb-Flat_Bench_Cable_Flyes', 'Плоская скамья на тросе'),
('fedb-Flat_Bench_Leg_Pull-In', 'Подтягивание ног на плоской скамье'),
('fedb-Flat_Bench_Lying_Leg_Raise', 'Подъем ног лежа на плоской скамье'),
('fedb-Flexor_Incline_Dumbbell_Curls', 'Сгибания гантелей на наклоне сгибателями'),
('fedb-Floor_Glute-Ham_Raise', 'Подъем ягодиц на полу с ветчиной'),
('fedb-Floor_Press', 'Напольный пресс'),
('fedb-Floor_Press_with_Chains', 'Жим с пола с цепями'),
('fedb-Flutter_Kicks', 'Флаттер-кики'),
('fedb-Foot-SMR', 'Фут-SMR'),
('fedb-Forward_Drag_with_Press', 'Перетаскивание вперед с нажатием'),
('fedb-Frankenstein_Squat', 'Франкенштейн приседания'),
('fedb-Freehand_Jump_Squat', 'Приседания с прыжком от руки'),
('fedb-Frog_Hops', 'Лягушачий хмель'),
('fedb-Frog_Sit-Ups', 'Приседания с лягушкой'),
('fedb-Front_Barbell_Squat', 'Приседания со штангой спереди'),
('fedb-Front_Barbell_Squat_To_A_Bench', 'Приседания со штангой спереди на скамье'),
('fedb-Front_Box_Jump', 'Передний прыжок с ящика'),
('fedb-Front_Cable_Raise', 'Подъем переднего троса'),
('fedb-Front_Cone_Hops_or_hurdle_hops', 'Передний конусный хмель (или прыжки с препятствиями)'),
('fedb-Front_Dumbbell_Raise', 'Подъем гантели спереди'),
('fedb-Front_Incline_Dumbbell_Raise', 'Подъем гантели вперед на наклонной скамье'),
('fedb-Front_Leg_Raises', 'Подъемы передних ног'),
('fedb-Front_Plate_Raise', 'Подъем передней пластины'),
('fedb-Front_Raise_And_Pullover', 'Подъем спереди и пуловер'),
('fedb-Front_Squat_Clean_Grip', 'Фронтальные приседания (чистый хват)'),
('fedb-Front_Squats_With_Two_Kettlebells', 'Фронтальные приседания с двумя гирями'),
('fedb-Front_Two-Dumbbell_Raise', 'Подъем двух гантелей спереди'),
('fedb-Full_Range-Of-Motion_Lat_Pulldown', 'Полный диапазон движений. Тяга широчайших мышц вниз'),
('fedb-Gironda_Sternum_Chins', 'Жиронда Грудина Подбородки'),
('fedb-Glute_Ham_Raise', 'Подъем ягодичной ветчины'),
('fedb-Glute_Kickback', 'Отдача ягодиц'),
('fedb-Goblet_Squat', 'Кубок приседаний'),
('fedb-Good_Morning', 'Доброе утро'),
('fedb-Good_Morning_off_Pins', 'Доброе утро!'),
('fedb-Gorilla_Chin_Crunch', 'Подбородок гориллы/Хруст'),
('fedb-Groin_and_Back_Stretch', 'Растяжка паха и спины'),
('fedb-Groiners', 'Гройнерс'),
('fedb-Hack_Squat', 'Гакк-приседания'),
('fedb-Hammer_Curls', 'Молотковые кудри'),
('fedb-Hammer_Grip_Incline_DB_Bench_Press', 'Жим лежа на наклонной скамье молотковым хватом'),
('fedb-Hamstring-SMR', 'Подколенное сухожилие-SMR'),
('fedb-Hamstring_Stretch', 'Растяжка подколенных сухожилий'),
('fedb-Handstand_Push-Ups', 'Отжимания в стойке на руках'),
('fedb-Hang_Clean', 'Повесьте чистоту'),
('fedb-Hang_Clean_-_Below_the_Knees', 'Вис на чистоте – ниже колен'),
('fedb-Hang_Snatch', 'Повесить рывок'),
('fedb-Hang_Snatch_-_Below_Knees', 'Рывок в подвешенном состоянии – ниже колен'),
('fedb-Hanging_Bar_Good_Morning', 'Подвесной бар «Доброе утро»'),
('fedb-Hanging_Leg_Raise', 'Подъем ног в висе'),
('fedb-Hanging_Pike', 'Висячая щука'),
('fedb-Heaving_Snatch_Balance', 'Баланс в рывке'),
('fedb-Heavy_Bag_Thrust', 'Упор тяжелой сумки'),
('fedb-High_Cable_Curls', 'Высокие завитки кабеля'),
('fedb-Hip_Circles_prone', 'Круговые движения бедрами (лежа)'),
('fedb-Hip_Extension_with_Bands', 'Разгибание бедер с помощью лент'),
('fedb-Hip_Flexion_with_Band', 'Сгибание бедра с помощью бандажа'),
('fedb-Hip_Lift_with_Band', 'Подтяжка бедер с лентой'),
('fedb-Hug_A_Ball', 'Обнять мяч'),
('fedb-Hug_Knees_To_Chest', 'Прижать колени к груди'),
('fedb-Hurdle_Hops', 'барьерный хмель'),
('fedb-Hyperextensions_Back_Extensions', 'Гиперэкстензии (разгибания спины)'),
('fedb-Hyperextensions_With_No_Hyperextension_Bench', 'Гиперэкстензии без скамьи для гиперэкстензии'),
('fedb-IT_Band_and_Glute_Stretch', 'IT Band и растяжка ягодиц'),
('fedb-Iliotibial_Tract-SMR', 'Илиотибиальный тракт-SMR'),
('fedb-Inchworm', 'дюймовый червь'),
('fedb-Incline_Barbell_Triceps_Extension', 'Разгибание трицепса со штангой на наклоне'),
('fedb-Incline_Bench_Pull', 'Тяга на наклонной скамье'),
('fedb-Incline_Cable_Chest_Press', 'Жим от груди с тросом на наклонной скамье'),
('fedb-Incline_Cable_Flye', 'Наклонная кабельная прокладка'),
('fedb-Incline_Dumbbell_Bench_With_Palms_Facing_In', 'Наклонная скамья с гантелями ладонями внутрь'),
('fedb-Incline_Dumbbell_Curl', 'Сгибание рук с гантелями на наклоне'),
('fedb-Incline_Dumbbell_Flyes', 'Разведение гантелей на наклонной скамье'),
('fedb-Incline_Dumbbell_Flyes_-_With_A_Twist', 'Разведение гантелей на наклонной скамье – с поворотом'),
('fedb-Incline_Dumbbell_Press', 'Жим гантелей на наклонной скамье'),
('fedb-Incline_Hammer_Curls', 'Сгибания молотков на наклоне'),
('fedb-Incline_Inner_Biceps_Curl', 'Сгибание внутреннего бицепса на наклоне'),
('fedb-Incline_Push-Up', 'Отжимания на наклоне'),
('fedb-Incline_Push-Up_Close-Grip', 'Отжимания на наклонной скамье узким хватом'),
('fedb-Incline_Push-Up_Depth_Jump', 'Прыжок в глубину отжиманий на наклонной скамье'),
('fedb-Incline_Push-Up_Medium', 'Отжимания на наклонной скамье, средние'),
('fedb-Incline_Push-Up_Reverse_Grip', 'Отжимания на наклоне обратным хватом'),
('fedb-Incline_Push-Up_Wide', 'Отжимания на наклоне в ширину'),
('fedb-Intermediate_Groin_Stretch', 'Промежуточная растяжка паха'),
('fedb-Intermediate_Hip_Flexor_and_Quad_Stretch', 'Промежуточный уровень сгибателей бедра и растяжка квадрицепсов'),
('fedb-Internal_Rotation_with_Band', 'Внутреннее вращение с лентой'),
('fedb-Inverted_Row', 'Перевернутая строка'),
('fedb-Inverted_Row_with_Straps', 'Перевернутый ряд с лямками'),
('fedb-Iron_Cross', 'Железный крест'),
('fedb-Iron_Crosses_stretch', 'Железные кресты (растяжка)'),
('fedb-Isometric_Chest_Squeezes', 'Изометрические сжимания груди'),
('fedb-Isometric_Neck_Exercise_-_Front_And_Back', 'Изометрическое упражнение для шеи — спереди и сзади'),
('fedb-Isometric_Neck_Exercise_-_Sides', 'Изометрическое упражнение для шеи — стороны'),
('fedb-Isometric_Wipers', 'Изометрические дворники'),
('fedb-JM_Press', 'ДжМ Пресс'),
('fedb-Jackknife_Sit-Up', 'Приседания на складном ноже'),
('fedb-Janda_Sit-Up', 'Янда приседания'),
('fedb-Jefferson_Squats', 'Джефферсон Приседания'),
('fedb-Jerk_Balance', 'Рывок на баланс'),
('fedb-Jerk_Dip_Squat', 'Приседания с толчком на брусьях'),
('fedb-Jogging_Treadmill', 'Бег трусцой, беговая дорожка'),
('fedb-Keg_Load', 'Загрузка бочонка'),
('fedb-Kettlebell_Arnold_Press', 'Гиря Арнольд Пресс'),
('fedb-Kettlebell_Dead_Clean', 'Гиря мертвая чистая'),
('fedb-Kettlebell_Figure_8', 'Гиря Рисунок 8'),
('fedb-Kettlebell_Hang_Clean', 'Гири висят на чистоте'),
('fedb-Kettlebell_One-Legged_Deadlift', 'Становая тяга с гирями на одной ноге'),
('fedb-Kettlebell_Pass_Between_The_Legs', 'Передача гири между ног'),
('fedb-Kettlebell_Pirate_Ships', 'Пиратские корабли с гирями'),
('fedb-Kettlebell_Pistol_Squat', 'Приседания с гирями-пистолетами'),
('fedb-Kettlebell_Seated_Press', 'Жим гири сидя'),
('fedb-Kettlebell_Seesaw_Press', 'Пресс для качелей с гирями'),
('fedb-Kettlebell_Sumo_High_Pull', 'Гиря сумо высокая тяга'),
('fedb-Kettlebell_Thruster', 'Гиря подруливающего устройства'),
('fedb-Kettlebell_Turkish_Get-Up_Lunge_style', 'Турецкий подъем с гирями (стиль выпадов)'),
('fedb-Kettlebell_Turkish_Get-Up_Squat_style', 'Турецкие подъемы с гирями (стиль приседаний)'),
('fedb-Kettlebell_Windmill', 'Ветряная мельница с гирями'),
('fedb-Kipping_Muscle_Up', 'Поднятие мышц вверх'),
('fedb-Knee_Across_The_Body', 'Колено по всему телу'),
('fedb-Knee_Circles', 'Коленные круги'),
('fedb-Knee_Hip_Raise_On_Parallel_Bars', 'Подъем колена/бедра на параллельных брусьях'),
('fedb-Knee_Tuck_Jump', 'Прыжок с подтягиванием колена'),
('fedb-Kneeling_Arm_Drill', 'Упражнение для рук на коленях'),
('fedb-Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists', 'Скручивания на тросе на коленях с попеременными наклонными скручиваниями'),
('fedb-Kneeling_Cable_Triceps_Extension', 'Разгибание трицепса на коленях'),
('fedb-Kneeling_Forearm_Stretch', 'Растяжка предплечий на коленях'),
('fedb-Kneeling_High_Pulley_Row', 'Тяга на высоком блоке на коленях'),
('fedb-Kneeling_Hip_Flexor', 'Сгибатель бедра на коленях'),
('fedb-Kneeling_Jump_Squat', 'Приседания с прыжком на коленях'),
('fedb-Kneeling_Single-Arm_High_Pulley_Row', 'Тяга на высоком блоке на одной руке на коленях'),
('fedb-Kneeling_Squat', 'Приседания на коленях'),
('fedb-Landmine_180s', 'Мина 180-х годов'),
('fedb-Landmine_Linear_Jammer', 'Линейный глушитель наземных мин'),
('fedb-Lateral_Bound', 'Боковая граница'),
('fedb-Lateral_Box_Jump', 'Боковой прыжок на коробку'),
('fedb-Lateral_Cone_Hops', 'Боковые конусные прыжки'),
('fedb-Lateral_Raise_-_With_Bands', 'Боковой подъем – с лентами'),
('fedb-Latissimus_Dorsi-SMR', 'Широчайшая мышца спины-SMR'),
('fedb-Leg-Over_Floor_Press', 'Жим ногами через пол'),
('fedb-Leg-Up_Hamstring_Stretch', 'Растяжка подколенных сухожилий при подъеме ноги вверх'),
('fedb-Leg_Extensions', 'Разгибания ног'),
('fedb-Leg_Lift', 'Подъем ног'),
('fedb-Leg_Press', 'Жим ногами'),
('fedb-Leg_Pull-In', 'Подтягивание ног'),
('fedb-Leverage_Chest_Press', 'Используйте жим от груди'),
('fedb-Leverage_Deadlift', 'Становая тяга с плечом'),
('fedb-Leverage_Decline_Chest_Press', 'Жим от груди с понижением рычага'),
('fedb-Leverage_High_Row', 'Используйте верхний ряд'),
('fedb-Leverage_Incline_Chest_Press', 'Жим от груди на наклонной скамье'),
('fedb-Leverage_Iso_Row', 'Используйте изо-строку'),
('fedb-Leverage_Shoulder_Press', 'Жим от плеч с рычагом'),
('fedb-Leverage_Shrug', 'Пожимание плечами'),
('fedb-Linear_3-Part_Start_Technique', 'Техника линейного старта из трех частей'),
('fedb-Linear_Acceleration_Wall_Drill', 'Настенная дрель с линейным ускорением'),
('fedb-Linear_Depth_Jump', 'Линейный прыжок в глубину'),
('fedb-Log_Lift', 'Бревенчатый подъемник'),
('fedb-London_Bridges', 'Лондонские мосты'),
('fedb-Looking_At_Ceiling', 'Глядя на потолок'),
('fedb-Low_Cable_Crossover', 'Низкий кабельный кроссовер'),
('fedb-Low_Cable_Triceps_Extension', 'Разгибание трицепса на низком тросе'),
('fedb-Low_Pulley_Row_To_Neck', 'Тяга на низком блоке к шее'),
('fedb-Lower_Back-SMR', 'Нижняя часть спины-SMR'),
('fedb-Lower_Back_Curl', 'Сгибание нижней части спины'),
('fedb-Lunge_Pass_Through', 'Выпад, проход насквозь'),
('fedb-Lunge_Sprint', 'Выпад-спринт'),
('fedb-Lying_Bent_Leg_Groin', 'Лежа, согнутая нога в паху'),
('fedb-Lying_Cable_Curl', 'Сгибание кабеля лежа'),
('fedb-Lying_Cambered_Barbell_Row', 'Тяга штанги лежа с прогибом'),
('fedb-Lying_Close-Grip_Bar_Curl_On_High_Pulley', 'Сгибание рук на грифе лежа узким хватом на верхнем блоке'),
('fedb-Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head', 'Разгибание трицепса лежа узким хватом за головой'),
('fedb-Lying_Close-Grip_Barbell_Triceps_Press_To_Chin', 'Жим штанги на трицепс лежа узким хватом к подбородку'),
('fedb-Lying_Crossover', 'Лежащий кроссовер'),
('fedb-Lying_Dumbbell_Tricep_Extension', 'Разгибание трицепса с гантелью лёжа'),
('fedb-Lying_Face_Down_Plate_Neck_Resistance', 'Сопротивление шеи лежа лицом вниз'),
('fedb-Lying_Face_Up_Plate_Neck_Resistance', 'Сопротивление шеи лежа лицом вверх'),
('fedb-Lying_Glute', 'Лежащая ягодица'),
('fedb-Lying_Hamstring', 'Лежа'),
('fedb-Lying_High_Bench_Barbell_Curl', 'Сгибание рук со штангой лежа на высокой скамье'),
('fedb-Lying_Leg_Curls', 'Сгибания ног лёжа'),
('fedb-Lying_Machine_Squat', 'Приседания в машине лежа'),
('fedb-Lying_One-Arm_Lateral_Raise', 'Подъем одной руки в стороны лежа'),
('fedb-Lying_Prone_Quadriceps', 'Квадрицепсы лежа лежа'),
('fedb-Lying_Rear_Delt_Raise', 'Подъем задних дельт лежа'),
('fedb-Lying_Supine_Dumbbell_Curl', 'Сгибание рук с гантелями лёжа на спине'),
('fedb-Lying_T-Bar_Row', 'Тяга Т-образных перекладин лежа'),
('fedb-Lying_Triceps_Press', 'Жим на трицепс лежа'),
('fedb-Machine_Bench_Press', 'Машинный жим лежа'),
('fedb-Machine_Bicep_Curl', 'Сгибание бицепса в машине'),
('fedb-Machine_Preacher_Curls', 'Машинные сгибания проповедника'),
('fedb-Machine_Shoulder_Military_Press', 'Жим от плеч на тренажере (военный)'),
('fedb-Machine_Triceps_Extension', 'Разгибание трицепса в тренажере'),
('fedb-Medicine_Ball_Chest_Pass', 'Пас на грудь с медболом'),
('fedb-Medicine_Ball_Full_Twist', 'Медбол, полный поворот'),
('fedb-Medicine_Ball_Scoop_Throw', 'Бросок набивного мяча'),
('fedb-Middle_Back_Shrug', 'Пожимание плечами средней части спины'),
('fedb-Middle_Back_Stretch', 'Растяжка средней части спины'),
('fedb-Mixed_Grip_Chin', 'Подбородок смешанным хватом'),
('fedb-Monster_Walk', 'Прогулка монстров'),
('fedb-Mountain_Climbers', 'Альпинисты'),
('fedb-Moving_Claw_Series', 'Серия движущихся когтей'),
('fedb-Muscle_Snatch', 'рывок мышц'),
('fedb-Muscle_Up', 'мышцы вверх'),
('fedb-Narrow_Stance_Hack_Squats', 'Гакк-приседания с узкой позицией'),
('fedb-Narrow_Stance_Leg_Press', 'Жим ногами в узкой стойке'),
('fedb-Narrow_Stance_Squats', 'Приседания с узкой стойкой'),
('fedb-Natural_Glute_Ham_Raise', 'Натуральный рейз с ветчиной для ягодиц'),
('fedb-Neck-SMR', 'Шея-SMR'),
('fedb-Neck_Press', 'Пресс для шеи'),
('fedb-Oblique_Crunches', 'Косые скручивания'),
('fedb-Oblique_Crunches_-_On_The_Floor', 'Косые скручивания — на полу'),
('fedb-Olympic_Squat', 'Олимпийские приседания'),
('fedb-On-Your-Back_Quad_Stretch', 'Растяжка квадрицепсов на спине'),
('fedb-On_Your_Side_Quad_Stretch', 'Растяжка квадрицепсов на боку'),
('fedb-One-Arm_Dumbbell_Row', 'Тяга гантели одной рукой'),
('fedb-One-Arm_Flat_Bench_Dumbbell_Flye', 'Гантель на плоской скамье на одной руке'),
('fedb-One-Arm_High-Pulley_Cable_Side_Bends', 'Боковые изгибы троса с одним рычагом и высоким шкивом'),
('fedb-One-Arm_Incline_Lateral_Raise', 'Подъём одной руки вбок на наклоне'),
('fedb-One-Arm_Kettlebell_Clean', 'Подъём гири одной рукой'),
('fedb-One-Arm_Kettlebell_Clean_and_Jerk', 'Гиря на одной руке в толчке'),
('fedb-One-Arm_Kettlebell_Floor_Press', 'Жим гири с пола одной рукой'),
('fedb-One-Arm_Kettlebell_Jerk', 'Толчок гири одной рукой'),
('fedb-One-Arm_Kettlebell_Military_Press_To_The_Side', 'Армейский жим гири одной рукой в сторону'),
('fedb-One-Arm_Kettlebell_Para_Press', 'Паралимпийский жим гири одной рукой'),
('fedb-One-Arm_Kettlebell_Push_Press', 'Жим гири одной рукой'),
('fedb-One-Arm_Kettlebell_Row', 'Тяга гири одной рукой'),
('fedb-One-Arm_Kettlebell_Snatch', 'Рывок гири одной рукой'),
('fedb-One-Arm_Kettlebell_Split_Jerk', 'Толчок гири одной рукой в шпагате'),
('fedb-One-Arm_Kettlebell_Split_Snatch', 'Рывок гири одной рукой в шпагате'),
('fedb-One-Arm_Kettlebell_Swings', 'Махи гири одной рукой'),
('fedb-One-Arm_Long_Bar_Row', 'Тяга штанги на одной руке'),
('fedb-One-Arm_Medicine_Ball_Slam', 'Удар набивным мячом одной рукой'),
('fedb-One-Arm_Open_Palm_Kettlebell_Clean', 'Подъём гири одной рукой с открытой ладонью'),
('fedb-One-Arm_Overhead_Kettlebell_Squats', 'Приседания с гирей на одной руке над головой'),
('fedb-One-Arm_Side_Deadlift', 'Становая тяга на одной руке'),
('fedb-One-Arm_Side_Laterals', 'Боковые упражнения на одной руке'),
('fedb-One-Legged_Cable_Kickback', 'Отдача на тросе на одной ноге'),
('fedb-One_Arm_Against_Wall', 'Одна рука к стене'),
('fedb-One_Arm_Chin-Up', 'Подтягивания на одной руке'),
('fedb-One_Arm_Dumbbell_Bench_Press', 'Жим гантели одной рукой'),
('fedb-One_Arm_Dumbbell_Preacher_Curl', 'Сгибание рук проповедника с гантелью одной рукой'),
('fedb-One_Arm_Floor_Press', 'Жим с пола одной рукой'),
('fedb-One_Arm_Lat_Pulldown', 'Тяга широчайших мышц одной рукой'),
('fedb-One_Arm_Pronated_Dumbbell_Triceps_Extension', 'Разгибание трицепса с гантелью одной рукой с пронацией'),
('fedb-One_Arm_Supinated_Dumbbell_Triceps_Extension', 'Разгибание трицепса с гантелью на одной руке с супинацией'),
('fedb-One_Half_Locust', 'Половина саранчи'),
('fedb-One_Handed_Hang', 'Вис одной рукой'),
('fedb-One_Knee_To_Chest', 'Одно колено к груди'),
('fedb-One_Leg_Barbell_Squat', 'Приседания со штангой на одной ноге'),
('fedb-Open_Palm_Kettlebell_Clean', 'Очистка гири открытой ладонью'),
('fedb-Otis-Up', 'Отис-Ап'),
('fedb-Overhead_Cable_Curl', 'Скручивание кабеля над головой'),
('fedb-Overhead_Lat', 'Над головой широчайшие'),
('fedb-Overhead_Slam', 'Удар над головой'),
('fedb-Overhead_Squat', 'Приседания над головой'),
('fedb-Overhead_Stretch', 'Растяжка над головой'),
('fedb-Overhead_Triceps', 'Трицепс над головой'),
('fedb-Pallof_Press', 'Паллоф Пресс'),
('fedb-Pallof_Press_With_Rotation', 'Пресс Паллофа с вращением'),
('fedb-Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench', 'Сгибание запястий с гантелью ладонями вниз над скамьей'),
('fedb-Palms-Down_Wrist_Curl_Over_A_Bench', 'Сгибание запястий ладонями вниз над скамьей'),
('fedb-Palms-Up_Barbell_Wrist_Curl_Over_A_Bench', 'Сгибание запястий со штангой ладонями вверх над скамьей'),
('fedb-Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench', 'Сгибание запястий с гантелью ладонями вверх над скамьей'),
('fedb-Parallel_Bar_Dip', 'Отжимание на параллельной перекладине'),
('fedb-Pelvic_Tilt_Into_Bridge', 'Наклон таза в мост'),
('fedb-Peroneals-SMR', 'Перонеалс-СМР'),
('fedb-Peroneals_Stretch', 'Растяжка перонеалов'),
('fedb-Physioball_Hip_Bridge', 'Тазобедренный мост с физиоболом'),
('fedb-Pin_Presses', 'Прессы для штифтов'),
('fedb-Piriformis-SMR', 'Пириформис-СМР'),
('fedb-Plank', 'Планка'),
('fedb-Plate_Pinch', 'Тарелка Пинч'),
('fedb-Plate_Twist', 'Пластина Твист'),
('fedb-Platform_Hamstring_Slides', 'Слайды на платформе для подколенных сухожилий'),
('fedb-Plie_Dumbbell_Squat', 'Приседания с гантелями в стиле плие'),
('fedb-Plyo_Kettlebell_Pushups', 'Плио отжимания с гирями'),
('fedb-Plyo_Push-up', 'Плио отжимания'),
('fedb-Posterior_Tibialis_Stretch', 'Растяжка задней большеберцовой мышцы'),
('fedb-Power_Clean', 'Силовая очистка'),
('fedb-Power_Clean_from_Blocks', 'Силовая очистка от блоков'),
('fedb-Power_Jerk', 'Мощность рывок'),
('fedb-Power_Partials', 'Части мощности'),
('fedb-Power_Snatch', 'Мощный рывок'),
('fedb-Power_Snatch_from_Blocks', 'Выхват мощности из блоков'),
('fedb-Power_Stairs', 'Лестницы с электроприводом'),
('fedb-Preacher_Curl', 'Проповедник Керл'),
('fedb-Preacher_Hammer_Dumbbell_Curl', 'Проповедник Молот Сгибание рук с гантелями'),
('fedb-Press_Sit-Up', 'Жим приседаниями'),
('fedb-Prone_Manual_Hamstring', 'Ручное подколенное сухожилие лежа'),
('fedb-Prowler_Sprint', 'Проулер Спринт'),
('fedb-Pull_Through', 'Вытащить через'),
('fedb-Pullups', 'Подтягивания'),
('fedb-Push-Up_Wide', 'Пуш-ап широкий'),
('fedb-Push-Ups_-_Close_Triceps_Position', 'Отжимания – закрытая позиция трицепса'),
('fedb-Push-Ups_With_Feet_Elevated', 'Отжимания с поднятыми ногами'),
('fedb-Push-Ups_With_Feet_On_An_Exercise_Ball', 'Отжимания с ногами на гимнастическом мяче'),
('fedb-Push_Press', 'Нажмите Пресс'),
('fedb-Push_Press_-_Behind_the_Neck', 'Толкающий пресс – из-за шеи'),
('fedb-Push_Up_to_Side_Plank', 'Отжимание до боковой планки'),
('fedb-Pushups', 'Отжимания'),
('fedb-Pushups_Close_and_Wide_Hand_Positions', 'Отжимания (близкие и широкие положения рук)'),
('fedb-Pyramid', 'Пирамида'),
('fedb-Quad_Stretch', 'Квад-стретч'),
('fedb-Quadriceps-SMR', 'Квадрицепс-SMR'),
('fedb-Quick_Leap', 'Быстрый прыжок'),
('fedb-Rack_Delivery', 'Доставка стойки'),
('fedb-Rack_Pull_with_Bands', 'Тяга в стойке с лентами'),
('fedb-Rack_Pulls', 'Тяги для стойки'),
('fedb-Rear_Leg_Raises', 'Подъемы задних ног'),
('fedb-Recumbent_Bike', 'Лежачий велосипед'),
('fedb-Return_Push_from_Stance', 'Ответный толчок из стойки'),
('fedb-Reverse_Band_Bench_Press', 'Жим лежа с обратной лентой'),
('fedb-Reverse_Band_Box_Squat', 'Приседания на ящик с обратным бинтом'),
('fedb-Reverse_Band_Deadlift', 'Становая тяга с обратной лентой'),
('fedb-Reverse_Band_Power_Squat', 'Силовые приседания с обратной лентой'),
('fedb-Reverse_Band_Sumo_Deadlift', 'Становая тяга сумо с обратной лентой'),
('fedb-Reverse_Barbell_Curl', 'Обратное сгибание рук со штангой'),
('fedb-Reverse_Barbell_Preacher_Curls', 'Обратные сгибания рук проповедника со штангой'),
('fedb-Reverse_Cable_Curl', 'Обратное скручивание кабеля'),
('fedb-Reverse_Crunch', 'Обратный кранч'),
('fedb-Reverse_Flyes', 'Обратные полеты'),
('fedb-Reverse_Flyes_With_External_Rotation', 'Обратные полеты с внешним вращением'),
('fedb-Reverse_Grip_Bent-Over_Rows', 'Тяга в наклоне обратным хватом'),
('fedb-Reverse_Grip_Triceps_Pushdown', 'Отжимание на трицепс обратным хватом'),
('fedb-Reverse_Hyperextension', 'Обратная гиперэкстензия'),
('fedb-Reverse_Machine_Flyes', 'Обратный полет машины'),
('fedb-Reverse_Plate_Curls', 'Сгибания рук с обратными пластинами'),
('fedb-Reverse_Triceps_Bench_Press', 'Обратный жим на трицепс лежа'),
('fedb-Rhomboids-SMR', 'Ромбоиды-СМР'),
('fedb-Rickshaw_Carry', 'Рикша Керри'),
('fedb-Rickshaw_Deadlift', 'Становая тяга на рикше'),
('fedb-Ring_Dips', 'Кольцевые провалы'),
('fedb-Rocket_Jump', 'Ракетный прыжок'),
('fedb-Rocking_Standing_Calf_Raise', 'Раскачивание, подъем на носки стоя'),
('fedb-Rocky_Pull-Ups_Pulldowns', 'Рокки-подтягивания/тяги вниз'),
('fedb-Romanian_Deadlift', 'Румынская становая тяга'),
('fedb-Romanian_Deadlift_from_Deficit', 'Румынская становая тяга от дефицита'),
('fedb-Rope_Climb', 'Подъем по веревке'),
('fedb-Rope_Crunch', 'Хруст веревки'),
('fedb-Rope_Jumping', 'Прыжки со скакалкой'),
('fedb-Rope_Straight-Arm_Pulldown', 'Тяга вниз на прямых руках со скакалкой'),
('fedb-Round_The_World_Shoulder_Stretch', 'Растяжка плеч вокруг света'),
('fedb-Rowing_Stationary', 'Гребля, Стационарный'),
('fedb-Runners_Stretch', 'Растяжка бегуна'),
('fedb-Running_Treadmill', 'Бег, Беговая дорожка'),
('fedb-Russian_Twist', 'Русский твист'),
('fedb-Sandbag_Load', 'Загрузка мешков с песком'),
('fedb-Scapular_Pull-Up', 'Подтягивания лопаток'),
('fedb-Scissor_Kick', 'ножничный удар'),
('fedb-Scissors_Jump', 'Ножницы Прыжок'),
('fedb-Seated_Band_Hamstring_Curl', 'Сгибание подколенных сухожилий с лентой сидя'),
('fedb-Seated_Barbell_Military_Press', 'Военный жим штанги сидя'),
('fedb-Seated_Barbell_Twist', 'Поворот штанги сидя'),
('fedb-Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension', 'Разгибание одной руки с гантелью на трицепс в наклоне сидя'),
('fedb-Seated_Bent-Over_Rear_Delt_Raise', 'Подъем задних дельт в наклоне сидя'),
('fedb-Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension', 'Разгибание трицепса с гантелью двумя руками в наклоне сидя'),
('fedb-Seated_Biceps', 'Бицепс сидя'),
('fedb-Seated_Cable_Rows', 'Сидячие кабельные ряды'),
('fedb-Seated_Cable_Shoulder_Press', 'Жим от плеч сидя на тросе'),
('fedb-Seated_Calf_Raise', 'Подъем на носки сидя'),
('fedb-Seated_Calf_Stretch', 'Растяжка икр сидя'),
('fedb-Seated_Close-Grip_Concentration_Barbell_Curl', 'Концентрированное сгибание штанги узким хватом сидя'),
('fedb-Seated_Dumbbell_Curl', 'Сгибание рук с гантелями сидя'),
('fedb-Seated_Dumbbell_Inner_Biceps_Curl', 'Сгибание внутреннего бицепса с гантелью сидя'),
('fedb-Seated_Dumbbell_Palms-Down_Wrist_Curl', 'Сгибание запястий с гантелью сидя, ладонями вниз'),
('fedb-Seated_Dumbbell_Palms-Up_Wrist_Curl', 'Сгибание запястий с гантелью сидя ладонями вверх'),
('fedb-Seated_Dumbbell_Press', 'Жим гантелей сидя'),
('fedb-Seated_Flat_Bench_Leg_Pull-In', 'Подтягивание ног на плоской скамье сидя'),
('fedb-Seated_Floor_Hamstring_Stretch', 'Растяжка подколенных сухожилий на полу сидя'),
('fedb-Seated_Front_Deltoid', 'Передние дельты сидя'),
('fedb-Seated_Glute', 'Сидящая ягодица'),
('fedb-Seated_Good_Mornings', 'Сидячее доброе утро'),
('fedb-Seated_Hamstring', 'Подколенное сухожилие сидя'),
('fedb-Seated_Hamstring_and_Calf_Stretch', 'Растяжка подколенных сухожилий и икр сидя'),
('fedb-Seated_Head_Harness_Neck_Resistance', 'Ремень безопасности для головы в положении сидя Сопротивление шеи'),
('fedb-Seated_Leg_Curl', 'Сгибание ног сидя'),
('fedb-Seated_Leg_Tucks', 'Подтягивания ног сидя'),
('fedb-Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl', 'Сгибание запястий с гантелью на одной руке сидя, ладонями вниз'),
('fedb-Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl', 'Сгибание запястья с гантелью на одной руке сидя'),
('fedb-Seated_One-arm_Cable_Pulley_Rows', 'Тяга на блоке сидя одной рукой'),
('fedb-Seated_Overhead_Stretch', 'Растяжка над головой сидя'),
('fedb-Seated_Palm-Up_Barbell_Wrist_Curl', 'Сгибание запястий со штангой сидя ладонями вверх'),
('fedb-Seated_Palms-Down_Barbell_Wrist_Curl', 'Сгибание запястий со штангой сидя ладонями вниз'),
('fedb-Seated_Side_Lateral_Raise', 'Боковой подъем сидя'),
('fedb-Seated_Triceps_Press', 'Жим трицепса сидя'),
('fedb-Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl', 'Сгибание запястий двумя руками вверх с низким блоком сидя'),
('fedb-See-Saw_Press_Alternating_Side_Press', 'See-Saw Press (попеременный боковой пресс)'),
('fedb-Shotgun_Row', 'Дробовик Роу'),
('fedb-Shoulder_Circles', 'Плечевые круги'),
('fedb-Shoulder_Press_-_With_Bands', 'Жим от плеч – с лентами'),
('fedb-Shoulder_Raise', 'Поднятие плеч'),
('fedb-Shoulder_Stretch', 'Растяжка плеч'),
('fedb-Side-Lying_Floor_Stretch', 'Растяжка на полу лежа на боку'),
('fedb-Side_Bridge', 'Боковой мост'),
('fedb-Side_Hop-Sprint', 'Боковой прыжок-спринт'),
('fedb-Side_Jackknife', 'Боковой складной нож'),
('fedb-Side_Lateral_Raise', 'Боковой боковой подъем'),
('fedb-Side_Laterals_to_Front_Raise', 'Боковые повороты к переднему подъему'),
('fedb-Side_Leg_Raises', 'Боковые подъемы ног'),
('fedb-Side_Lying_Groin_Stretch', 'Растяжка паха на боку лежа'),
('fedb-Side_Neck_Stretch', 'Боковая растяжка шеи'),
('fedb-Side_Standing_Long_Jump', 'Прыжок в длину с места на боку'),
('fedb-Side_To_Side_Chins', 'Подбородки из стороны в сторону'),
('fedb-Side_Wrist_Pull', 'Боковая тяга запястья'),
('fedb-Side_to_Side_Box_Shuffle', 'Перетасовка коробки из стороны в сторону'),
('fedb-Single-Arm_Cable_Crossover', 'Однорычажный кабельный кроссовер'),
('fedb-Single-Arm_Linear_Jammer', 'Однорычажный линейный глушитель'),
('fedb-Single-Arm_Push-Up', 'Отжимания на одной руке'),
('fedb-Single-Cone_Sprint_Drill', 'Одноконусное спринтерское упражнение'),
('fedb-Single-Leg_High_Box_Squat', 'Приседания на ящик на одной ноге'),
('fedb-Single-Leg_Hop_Progression', 'Прогрессия прыжков на одной ноге'),
('fedb-Single-Leg_Lateral_Hop', 'Боковой прыжок на одной ноге'),
('fedb-Single-Leg_Leg_Extension', 'Разгибание ног на одной ноге'),
('fedb-Single-Leg_Stride_Jump', 'Прыжок с шагом на одной ноге'),
('fedb-Single_Dumbbell_Raise', 'Одиночный подъем гантели'),
('fedb-Single_Leg_Butt_Kick', 'Удар ногой одной ногой'),
('fedb-Single_Leg_Glute_Bridge', 'Ягодичный мостик на одной ноге'),
('fedb-Single_Leg_Push-off', 'Отталкивание на одной ноге'),
('fedb-Sit-Up', 'Приседания'),
('fedb-Sit_Squats', 'Сидячие приседания'),
('fedb-Skating', 'Катание на коньках'),
('fedb-Sled_Drag_-_Harness', 'Sled Drag - Упряжь'),
('fedb-Sled_Overhead_Backward_Walk', 'Ходьба назад над головой на санях'),
('fedb-Sled_Overhead_Triceps_Extension', 'Разгибание трицепса над головой на санях'),
('fedb-Sled_Push', 'Санный толчок'),
('fedb-Sled_Reverse_Flye', 'Сани Реверс Флай'),
('fedb-Sled_Row', 'Санный ряд'),
('fedb-Sledgehammer_Swings', 'Качели с кувалдой'),
('fedb-Smith_Incline_Shoulder_Raise', 'Подъем плеч Смита на наклонной скамье'),
('fedb-Smith_Machine_Behind_the_Back_Shrug', 'Шраги за спиной в машине Смита'),
('fedb-Smith_Machine_Bench_Press', 'Жим лежа в машине Смита'),
('fedb-Smith_Machine_Bent_Over_Row', 'Тяга в наклоне в тренажере Смита'),
('fedb-Smith_Machine_Calf_Raise', 'Подъем на носки в машине Смита'),
('fedb-Smith_Machine_Close-Grip_Bench_Press', 'Жим лежа узким хватом в машине Смита'),
('fedb-Smith_Machine_Decline_Press', 'Жим наклона машины Смита'),
('fedb-Smith_Machine_Hang_Power_Clean', 'Подвес в тренажере Смита Power Clean'),
('fedb-Smith_Machine_Hip_Raise', 'Подъем бедра в машине Смита'),
('fedb-Smith_Machine_Incline_Bench_Press', 'Жим лежа на наклонной скамье в машине Смита'),
('fedb-Smith_Machine_Leg_Press', 'Жим ногами в машине Смита'),
('fedb-Smith_Machine_One-Arm_Upright_Row', 'Тяга одной рукой вертикально в тренажере Смита'),
('fedb-Smith_Machine_Overhead_Shoulder_Press', 'Жим от плеч в машине Смита над головой'),
('fedb-Smith_Machine_Pistol_Squat', 'Приседания с пистолетом в машине Смита'),
('fedb-Smith_Machine_Reverse_Calf_Raises', 'Подъемы на носки обратным ходом в машине Смита'),
('fedb-Smith_Machine_Squat', 'Приседания в машине Смита'),
('fedb-Smith_Machine_Stiff-Legged_Deadlift', 'Становая тяга на прямых ногах в машине Смита'),
('fedb-Smith_Machine_Upright_Row', 'Тяга вертикальных тяг в машине Смита'),
('fedb-Smith_Single-Leg_Split_Squat', 'Приседания Смита на одной ноге со шпагатом'),
('fedb-Snatch', 'урвать'),
('fedb-Snatch_Balance', 'Рывок баланса'),
('fedb-Snatch_Deadlift', 'Становая тяга в рывке'),
('fedb-Snatch_Pull', 'Рывок, тяга'),
('fedb-Snatch_Shrug', 'Пожать плечами'),
('fedb-Snatch_from_Blocks', 'Вырвать из блоков'),
('fedb-Speed_Band_Overhead_Triceps', 'Скоростной диапазон на трицепс над головой'),
('fedb-Speed_Box_Squat', 'Приседания на скоростной ящик'),
('fedb-Speed_Squats', 'Скоростные приседания'),
('fedb-Spell_Caster', 'Заклинатель'),
('fedb-Spider_Crawl', 'Паучье ползание'),
('fedb-Spider_Curl', 'Паучий завиток'),
('fedb-Spinal_Stretch', 'Растяжка позвоночника'),
('fedb-Split_Clean', 'Сплит Чистый'),
('fedb-Split_Jerk', 'Сплит-рывок'),
('fedb-Split_Jump', 'Сплит-прыжок'),
('fedb-Split_Snatch', 'Сплит-рывок'),
('fedb-Split_Squat_with_Dumbbells', 'Сплит-приседания с гантелями'),
('fedb-Split_Squats', 'Сплит-приседания'),
('fedb-Squat_Jerk', 'Приседания с толчком'),
('fedb-Squat_with_Bands', 'Приседания с лентами'),
('fedb-Squat_with_Chains', 'Приседания с цепями'),
('fedb-Squat_with_Plate_Movers', 'Приседания с движениями тарелок'),
('fedb-Squats_-_With_Bands', 'Приседания – с лентами'),
('fedb-Stairmaster', 'Лестничный мастер'),
('fedb-Standing_Alternating_Dumbbell_Press', 'Попеременный жим гантелей стоя'),
('fedb-Standing_Barbell_Calf_Raise', 'Подъем штанги на носки стоя'),
('fedb-Standing_Barbell_Press_Behind_Neck', 'Жим штанги стоя из-за шеи'),
('fedb-Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension', 'Разгибание одной руки с гантелью на трицепс в наклоне стоя'),
('fedb-Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension', 'Разгибание трицепса с гантелью двумя руками стоя в наклоне'),
('fedb-Standing_Biceps_Cable_Curl', 'Сгибание рук на бицепс стоя'),
('fedb-Standing_Biceps_Stretch', 'Растяжка бицепса стоя'),
('fedb-Standing_Bradford_Press', 'Стэндинг Брэдфорд Пресс'),
('fedb-Standing_Cable_Chest_Press', 'Жим от груди стоя на тросе'),
('fedb-Standing_Cable_Lift', 'Постоянный кабельный подъемник'),
('fedb-Standing_Cable_Wood_Chop', 'Рубить дрова стоящим кабелем'),
('fedb-Standing_Calf_Raises', 'Подъемы на носки стоя'),
('fedb-Standing_Concentration_Curl', 'Концентрированное сгибание рук стоя'),
('fedb-Standing_Dumbbell_Calf_Raise', 'Подъем гантели на носки стоя'),
('fedb-Standing_Dumbbell_Press', 'Жим гантелей стоя'),
('fedb-Standing_Dumbbell_Reverse_Curl', 'Обратное сгибание рук с гантелью стоя'),
('fedb-Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head', 'Гантель стоя, подъем передних дельт над головой'),
('fedb-Standing_Dumbbell_Triceps_Extension', 'Разгибание трицепса с гантелью стоя'),
('fedb-Standing_Dumbbell_Upright_Row', 'Тяга гантелей в вертикальном положении стоя'),
('fedb-Standing_Elevated_Quad_Stretch', 'Растяжка квадрицепсов стоя'),
('fedb-Standing_Front_Barbell_Raise_Over_Head', 'Подъем штанги спереди стоя над головой'),
('fedb-Standing_Gastrocnemius_Calf_Stretch', 'Растяжка икроножных мышц стоя'),
('fedb-Standing_Hamstring_and_Calf_Stretch', 'Растяжка подколенных сухожилий и икр стоя'),
('fedb-Standing_Hip_Circles', 'Круги бедрами стоя'),
('fedb-Standing_Hip_Flexors', 'Сгибатели бедра стоя'),
('fedb-Standing_Inner-Biceps_Curl', 'Сгибание внутренних мышц бицепса стоя'),
('fedb-Standing_Lateral_Stretch', 'Боковая растяжка стоя'),
('fedb-Standing_Leg_Curl', 'Сгибание ног стоя'),
('fedb-Standing_Long_Jump', 'Прыжок в длину с места'),
('fedb-Standing_Low-Pulley_Deltoid_Raise', 'Подъем дельтовидных мышц стоя на низком блоке'),
('fedb-Standing_Low-Pulley_One-Arm_Triceps_Extension', 'Разгибание одной руки на трицепс стоя с низким блоком'),
('fedb-Standing_Military_Press', 'Постоянная военная пресса'),
('fedb-Standing_Olympic_Plate_Hand_Squeeze', 'Сжимание руками олимпийского блина стоя'),
('fedb-Standing_One-Arm_Cable_Curl', 'Сгибание рук на тросе стоя'),
('fedb-Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench', 'Сгибание гантели одной рукой на наклонной скамье стоя'),
('fedb-Standing_One-Arm_Dumbbell_Triceps_Extension', 'Разгибание трицепса с гантелью на одной руке стоя'),
('fedb-Standing_Overhead_Barbell_Triceps_Extension', 'Разгибание трицепса со штангой над головой стоя'),
('fedb-Standing_Palm-In_One-Arm_Dumbbell_Press', 'Жим гантели одной рукой стоя, ладонь внутрь'),
('fedb-Standing_Palms-In_Dumbbell_Press', 'Жим гантелей стоя на ладонях стоя'),
('fedb-Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl', 'Сгибание запястий со штангой стоя за спиной'),
('fedb-Standing_Pelvic_Tilt', 'Наклон таза стоя'),
('fedb-Standing_Rope_Crunch', 'Скручивание веревки стоя'),
('fedb-Standing_Soleus_And_Achilles_Stretch', 'Растяжка камбаловидной мышцы и ахилла стоя'),
('fedb-Standing_Toe_Touches', 'Прикосновения пальцев ног стоя'),
('fedb-Standing_Towel_Triceps_Extension', 'Разгибание трицепса стоя на полотенце'),
('fedb-Standing_Two-Arm_Overhead_Throw', 'Бросок двумя руками через голову стоя'),
('fedb-Star_Jump', 'Звездный прыжок'),
('fedb-Step-up_with_Knee_Raise', 'Шаг вперед с подъемом колена'),
('fedb-Step_Mill', 'Шаг Мельница'),
('fedb-Stiff-Legged_Barbell_Deadlift', 'Становая тяга со штангой на прямых ногах'),
('fedb-Stiff-Legged_Dumbbell_Deadlift', 'Становая тяга с гантелями на прямых ногах'),
('fedb-Stiff_Leg_Barbell_Good_Morning', 'Штанга с жесткими ногами, доброе утро'),
('fedb-Stomach_Vacuum', 'Желудочный вакуум'),
('fedb-Straight-Arm_Dumbbell_Pullover', 'Пуловер с гантелями на прямых руках'),
('fedb-Straight-Arm_Pulldown', 'Тяга вниз на прямых руках'),
('fedb-Straight_Bar_Bench_Mid_Rows', 'Прямая скамья со штангой в средних рядах'),
('fedb-Straight_Raises_on_Incline_Bench', 'Прямые подъемы на наклонной скамье'),
('fedb-Stride_Jump_Crossover', 'Страйд-джамп-кроссовер'),
('fedb-Sumo_Deadlift', 'Становая тяга сумо'),
('fedb-Sumo_Deadlift_with_Bands', 'Становая тяга сумо с лентами'),
('fedb-Sumo_Deadlift_with_Chains', 'Становая тяга сумо с цепями'),
('fedb-Superman', 'Супермен'),
('fedb-Supine_Chest_Throw', 'Бросок на грудь лежа на спине'),
('fedb-Supine_One-Arm_Overhead_Throw', 'Бросок одной рукой через голову лежа на спине'),
('fedb-Supine_Two-Arm_Overhead_Throw', 'Бросок двумя руками через голову лежа на спине'),
('fedb-Suspended_Fallout', 'Приостановленные последствия'),
('fedb-Suspended_Push-Up', 'Отжимания с подвесом'),
('fedb-Suspended_Reverse_Crunch', 'Обратный кранч с подвесом'),
('fedb-Suspended_Row', 'Приостановленный ряд'),
('fedb-Suspended_Split_Squat', 'Сплит-приседания с подвесом'),
('fedb-Svend_Press', 'Свенд Пресс'),
('fedb-T-Bar_Row_with_Handle', 'Тяга Т-образного перекладины с ручкой'),
('fedb-Tate_Press', 'Тейт Пресс'),
('fedb-The_Straddle', 'Стрэддл'),
('fedb-Thigh_Abductor', 'Похититель бедра'),
('fedb-Thigh_Adductor', 'Приводящая мышца бедра'),
('fedb-Tire_Flip', 'Переворот шины'),
('fedb-Toe_Touchers', 'касания пальцев ног'),
('fedb-Torso_Rotation', 'Вращение туловища'),
('fedb-Trail_Running_Walking', 'Бег по пересеченной местности/ходьба'),
('fedb-Trap_Bar_Deadlift', 'Становая тяга с трэп-штангой'),
('fedb-Tricep_Dumbbell_Kickback', 'Отдача гантели на трицепс'),
('fedb-Tricep_Side_Stretch', 'Боковая растяжка трицепса'),
('fedb-Triceps_Overhead_Extension_with_Rope', 'Разгибание над головой на трицепс со скакалкой'),
('fedb-Triceps_Pushdown', 'Отжимание на трицепс'),
('fedb-Triceps_Pushdown_-_Rope_Attachment', 'Отжимание на трицепс вниз — крепление на веревке'),
('fedb-Triceps_Pushdown_-_V-Bar_Attachment', 'Отжимание на трицепс вниз – приспособление для V-образной перекладины'),
('fedb-Triceps_Stretch', 'Растяжка трицепса'),
('fedb-Tuck_Crunch', 'Так хруст'),
('fedb-Two-Arm_Dumbbell_Preacher_Curl', 'Сгибание рук проповедника с гантелью двумя руками'),
('fedb-Two-Arm_Kettlebell_Clean', 'Подъём гири двумя руками'),
('fedb-Two-Arm_Kettlebell_Jerk', 'Толчок гири двумя руками'),
('fedb-Two-Arm_Kettlebell_Military_Press', 'Армейский жим гири двумя руками'),
('fedb-Two-Arm_Kettlebell_Row', 'Тяга гири двумя руками'),
('fedb-Underhand_Cable_Pulldowns', 'Тяга вниз на тросе снизу'),
('fedb-Upper_Back-Leg_Grab', 'Захват верхней части задней ноги'),
('fedb-Upper_Back_Stretch', 'Растяжка верхней части спины'),
('fedb-Upright_Barbell_Row', 'Тяга штанги вертикально'),
('fedb-Upright_Cable_Row', 'Вертикальный кабельный ряд'),
('fedb-Upright_Row_-_With_Bands', 'Вертикальный ряд – с лентами'),
('fedb-Upward_Stretch', 'Растяжка вверх'),
('fedb-V-Bar_Pulldown', 'Тяга V-образной перекладины вниз'),
('fedb-V-Bar_Pullup', 'Подтягивания на V-образной перекладине'),
('fedb-Vertical_Swing', 'Вертикальное качание'),
('fedb-Walking_Treadmill', 'Ходьба, Беговая дорожка'),
('fedb-Weighted_Ball_Hyperextension', 'Гиперэкстензия на мяче с отягощением'),
('fedb-Weighted_Ball_Side_Bend', 'Наклон мяча в сторону с отягощением'),
('fedb-Weighted_Bench_Dip', 'Отжимания на скамье с отягощением'),
('fedb-Weighted_Crunches', 'Скручивания с отягощением'),
('fedb-Weighted_Jump_Squat', 'Приседания с прыжком с весом'),
('fedb-Weighted_Pull_Ups', 'Подтягивания с весом'),
('fedb-Weighted_Sissy_Squat', 'Приседания сисси с утяжелением'),
('fedb-Weighted_Sit-Ups_-_With_Bands', 'Приседания с отягощением — с лентами'),
('fedb-Weighted_Squat', 'Приседания с весом'),
('fedb-Wide-Grip_Barbell_Bench_Press', 'Жим штанги лежа широким хватом'),
('fedb-Wide-Grip_Decline_Barbell_Bench_Press', 'Жим штанги лежа широким хватом на наклонной скамье'),
('fedb-Wide-Grip_Decline_Barbell_Pullover', 'Пуловер со штангой со спуском и широким хватом'),
('fedb-Wide-Grip_Lat_Pulldown', 'Тяга широчайших мышц широким хватом'),
('fedb-Wide-Grip_Pulldown_Behind_The_Neck', 'Тяга вниз широким хватом из-за шеи'),
('fedb-Wide-Grip_Rear_Pull-Up', 'Задние подтягивания широким хватом'),
('fedb-Wide-Grip_Standing_Barbell_Curl', 'Сгибание рук со штангой стоя широким хватом'),
('fedb-Wide_Stance_Barbell_Squat', 'Приседания со штангой в широкой стойке'),
('fedb-Wide_Stance_Stiff_Legs', 'Широкая стойка, жесткие ноги'),
('fedb-Wind_Sprints', 'Ветровые спринты'),
('fedb-Windmills', 'Ветряные мельницы'),
('fedb-Worlds_Greatest_Stretch', 'Величайшая растяжка в мире'),
('fedb-Wrist_Circles', 'Круги на запястьях'),
('fedb-Wrist_Roller', 'Наручный ролик'),
('fedb-Wrist_Rotations_with_Straight_Bar', 'Вращения запястьями с прямой перекладиной'),
('fedb-Yoke_Walk', 'Хомут Прогулка'),
('fedb-Zercher_Squats', 'Приседания Зерхера'),
('fedb-Zottman_Curl', 'Зоттман Керл'),
('fedb-Zottman_Preacher_Curl', 'Зоттман Проповедник Керл')
) AS v(ext, ru)
WHERE e.external_id = v.ext;
